### ISSUE TITLE
[FEAT] placeholder suggestion

### ISSUE THREAD

**Issue by mikoloism** [wonize/boilerplate-generator#4]
what if use handlebar syntax as placeholder to replace with inputs instead of use curly brackets placeholder

``` yaml
name: 'Example Typescript'
boilerplates:
    - name: 'typescript-react-enum'
      boilerplate:
          - '<%=NAME {case: kebab}%>.enum.ts': |2
                export const enum <%=NAME%> {
                    <%for ITEM:ITEMS%>
                    <%=ITEM {case: constants}%> = <%=ITEM {case: kebab}%>
                    <%endfor%>
                }
                export type <%=NAME%>Type = <%=NAME%> | `${<%=NAME%>}`
```

**Comment by mikoloism** [comment]
what about `[> placeholder <]`, `{> placeholder <}`, `(> function placeholder <)` instead?

example:

``` yaml
name: 'Example Typescript'
boilerplates:
    - name: 'enum boilerplate'
      boilerplate:
          - '{> NAME | def:my-enum | case:kebab-case <}.enum.ts': |2
                // [> time: @.TIMESTAMP <]
                // [> version: @.env.PROJECT_VERSION <]

                export const enum {> NAME | def:MyEnum | case:pascal-case <} {
                    (> ITEM[] | range:1..Infinity <)
                    {> ITEM | case:constants-case <} = "{> ITEM | case:kebab-case <}"
                    (> ITEM[] <)
                }
                export type {> NAME | def:MyEnum | case:pascal-case <}{> $(select) TYPE_SUFIX | def:Type | options:[Type, Kind] <} = {> NAME | def:MyEnum | case:pascal-case<} | `${{> NAME | def:MyEnum | case:pascal-case <}}`

```

**Comment by mikoloism** [comment]
what if we give all variables as another part and merge it with boilerplates?

example:

``` yaml
name: 'Example Typescript'
boilerplates:
    - name: 'enum boilerplate'
      input:
          - type: text
            name: FILE_NAME
            default: my-enum
            question: what is file name?
          - type: select
            options:
                - Type
                - Kind
            name: TYPE_SUFFIX
            default: Type
            question: what is export type suffix?
          - type: loop
            range: 1..Infinity
            name: ENUM_KEYS
            question: what is enum key?
      boilerplate:
          - '{> NAME | case:kebab-case <}.enum.ts': |2
                // [> time: @.TIMESTAMP <]
                // [> version: @.env.PROJECT_VERSION <]

                export const enum {> NAME | case:pascal-case <} {
                    {> ENUM_KEYS[$$] | case:constants-case <} = "{> ENUM_KEYS[$$] | case:kebab-case <}"
                }
                export type {> NAME | case:pascal-case <}{> TYPE_SUFFIX  <} = {> NAME | case:pascal-case<} | `${{> NAME | case:pascal-case <}}`

```
